---

- block:
    - name: "{{ name }} Post results"
      import_role:
        name: post-results
  vars:
    status: "{{ 'SAPHanaSR' in ansible_facts.packages and ansible_facts.packages['SAPHanaSR'][0].version is version(expected[name], '>=') }}"
