---

- name: "{{ name }}.check"
  shell: |
    #  HANA and SPS versions are compatible
    sid=$(crm configure show | grep -m1 SID= | sed -e "s/.*SID=\(...\).*/\1/" | tr '[:upper:]' '[:lower:]')
    full_version=$(su -lc "HDB version" ${sid}adm | grep "version:" | sed -e "s/^.*:[\ ]*//")
    if [[ "$full_version" = "" ]]; then
      echo "0"
    else
      echo "$full_version"
    fi
  check_mode: false
  register: config_updated
  changed_when: config_updated.stdout is version(expected[name], '<')
  failed_when: config_updated.rc > 0

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ config_updated is not changed }}"
