---

- name: "Get HANA and SPS versions"
  shell: |
    #  HANA and SPS versions are compatible
    sid=$(crm configure show | grep -m1 SID= | sed -e "s/.*SID=\(...\).*/\1/" | tr '[:upper:]' '[:lower:]')
    full_version=$(su -lc "HDB version" ${sid}adm | grep "version:" | sed -e "s/^.*:[\ ]*//")
    echo "$full_version"
  register: spshana_version_reg
  check_mode: false
  changed_when: false
  
- name: "{{ name }} store HANA and SPS version as a fact"
  set_fact:
    spshana_version: "{{ spshana_version_reg.stdout }}"
  delegate_facts: true

- name: "{{ name }} compare HANA and SPS versions across nodes"
  assert:
    that:
      - "{{ groups[item] | map('extract', hostvars) | map(attribute='spshana_version') | list | unique | length }} == 1"
    quiet: true
  loop: "{{ group_names }}"
  register: config_updated
  changed_when: config_updated.failed
  when: "spshana_version is defined"

- block:
    - name: "{{ name }} Post results"
      import_role:
        name: post-results
  vars:
    status: "{{ spshana_version is defined and config_updated is not changed }}"
