---

name: 2.2.6
group: OS and package versions
labels: hana
description: |
  Test if installed SAPHanaSR version is supported
remediation: |
  ## Abstract
  Installed SAPHanaSR version must be equal or higher than {{ expected['2.2.6'] }}

  ## Remediation
  Install or upgrade to a supported SAPHanaSR version

  ## Reference
  - https://documentation.suse.com/en-us/sbp/all/single-html/SLES4SAP-hana-sr-guide-PerfOpt-15/
implementation: "{{ lookup('file', 'roles/checks/'+name+'/tasks/main.yml') }}"

# check id. This value must not be changed over the life of this check
id: 31BDCB
