---

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- block:
    - name: Post results
      import_role:
        name: post-results
  when:
    - ansible_check_mode
  vars:
    status: "{{ emacs is version('25.3.1', '>=') }}"
